### ISSUE TITLE
token_path mentioned under wrong section

### ISSUE THREAD

**Issue by uday-rayala** [linkyard/concourse-helm-resource#100]
It looks like `token_path` is mentioned user `Source Configuration` section in README where as the it should be provided as params according to https://github.com/linkyard/concourse-helm-resource/blob/master/assets/common.sh#L19

It took me a while to find out why my configuration was not working. I hope fixing the documentation it will help others.

**Comment by msiegenthaler** [comment]
Good catch, thanks a lot
