### ISSUE TITLE
check resource fails when source.release != params.release

### ISSUE THREAD

**Issue by Typositoire** [linkyard/concourse-helm-resource#113]
It is fundamentally flawed to check for `source.release` if you can overwrite it in `params.release`

This cause all the current check to fail if you installed a chart and overwrite the release name with `params.release`.

I don't know what would be the best approach to fix that but you can't access `params` in check.

My current use case is PR generate multiple parallel runs of a pipeline. I need to namespace some stuff by commitID to avoid clashes. I don't know said commitID before so I overwrite the release name on `put` which causes the check to fail because the release in source doesn't exist. I think we should overall make the resource release agnostic by default (remove source.release)  but then I have no idea what check we could perform..

**Comment by msiegenthaler** [comment]
I use it the other way, for me only the source one is relevant. And ad you say there’s no way to check for the params release. 
But I think you’ll never use it anyway, I can’t see a Pipeline where you use „dynamic“ releases and checks together so I suggest we add a flag to basically disable check.

**Comment by Typositoire** [comment]
Actually if you want to take a look at https://github.com/linkyard/concourse-helm-resource/pull/116

**Comment by Typositoire** [comment]
I'm sure there's a `legit` way of achieving both. Right now it's just annoying to see Yellow in concourse :p

**Comment by msiegenthaler** [comment]
This should be ok now, right?

**Comment by Typositoire** [comment]
Pretty sure it's not longer an issue.
