### ISSUE TITLE
Release tillerless tag

### ISSUE THREAD

**Issue by Typositoire** [linkyard/concourse-helm-resource#114]
I know I'm annoying :P Can you please release the version with tillerless option ?

**Comment by msiegenthaler** [comment]
Will do. I’ve already pushed an unofficial one to dockerhub (2.13.1-tillerless) as well as latest which also has tillerless support.
Actually we moved most out helms to tillerless now and since the version does not matter much I started using latest now.

**Comment by Typositoire** [comment]
Well versions matter less. There's probably some cases where you want a given versions xD

Thanks! I'll test out latest!

**Comment by Typositoire** [comment]
Also, just found a semi-bug. You can't overwrite tiller-namespace in `out` which now comes handy with tillerless ! I'll issue another PR.

**Comment by msiegenthaler** [comment]
I'll close this issue, you can always open another one for the tiller-namespace
