### ISSUE TITLE
Querying too many releases at the end of a build causes the build to fail

### ISSUE THREAD

**Issue by Anonymous-Coward** [linkyard/concourse-helm-resource#129]
This line in the out script:

`$helm_bin history $tls_flag --tiller-namespace $tiller_namespace --max 20 $release | grep "DEPLOYED"`

`--max 20` causes this error message:

`Error: grpc: trying to send message larger than max (29588589 vs. 20971520)`

This is an inherent helm problem, not something specific to this image. But making the `20` configurable via source, or setting it to something smaller, like 3, would IMO still achieve the goal while reducing the frequency of the error.

A helm chart to use for demo purposes: stable/prometheus-operator. It will fail for any --max <n> with n > 10, after there's enough releases to query.

**Comment by robwruck** [comment]
If you don't really need that many releases in your history, you could just install tiller manually using
```
helm init --history-max 3
```

**Comment by Anonymous-Coward** [comment]
In an enterprise setting, the ones in control of the pipelines don't always control tiller.

I currently deploy from concourse to multiple clusters. In one of them I'm not even allowed to touch the tiller version.

**Comment by jbialy** [comment]
@msiegenthaler, would you welcome a PR that adds the option to override the `--max` argument that's being passed to the `$helm_bin history ...` command?

**Comment by msiegenthaler** [comment]
Yes, I'd welcome it!

**Comment by jbialy** [comment]
> Yes, I'd welcome it!

That's great, I'm going to put together the PR with the changes today. I'm also wondering, would it be possible for you to merge the change (if approved of course) into version `2.13.1` (https://github.com/linkyard/concourse-helm-resource/tree/2.13.1) as well as the latest? 

We are still using tiller version < 2.14.x.

**Comment by msiegenthaler** [comment]
Thanks a lot, I've also pushed `2.13.1-1` specially for you 😄

**Comment by jbialy** [comment]
Thank you @msiegenthaler ! 🙇
