### ISSUE TITLE
Request update to 2.16.6

### ISSUE THREAD

**Issue by u2g-tg** [linkyard/concourse-helm-resource#140]
@msiegenthaler Could you please do the magic again and update to https://github.com/helm/helm/releases/tag/v2.16.6 

We've got an annoying issue caused by the null pointer thing fixed here (helm deploys work fine, but exit badly causing red Concourse tasks)

**Comment by msiegenthaler** [comment]
done, it's now available from dockerhub

**Comment by u2g-tg** [comment]
Brilliant, many thanks.
