### ISSUE TITLE
Request update to 2.17.0

### ISSUE THREAD

**Issue by martinxsliu** [linkyard/concourse-helm-resource#147]
Hi all! I'm requesting a new image published for [Helm 2.17.0](https://github.com/helm/helm/releases/tag/v2.17.0).

The stable and incubator repositories have moved to a new location ([here](https://helm.sh/blog/new-location-stable-incubator-charts/)) and it seems the old locations have just been switched off. The 2.17 version contains the new locations so we are blocked until we upgrade. Thanks!

**Comment by Tibernut** [comment]
+1 
As a temporary fix you can define stable_repo under your resources

```
source:
  stable_repo: https://charts.helm.sh/stable
```

**Comment by msiegenthaler** [comment]
Thanks for the reminder! 
linkyard/concourse-helm-resource:2.17.0 is now released
