### ISSUE TITLE
Support for custom chart repos

### ISSUE THREAD

**Issue by msiegenthaler** [linkyard/concourse-helm-resource#18]
Currently only the standard chart repos are support. Allow to specify the repo in the resource configuration.

Some work regarding this was done at https://github.com/thebeefcake/concourse-helm-resource
in commit b2ed6900cce782e74be24c488755a23b12a70942, e572d8ba67de3fb8beae1de592f24253154bdbcb, ad57e07e7ddce0144d2954ae86b39272858a8280, 99aab74892febe88e989cd90543e8466adb77587

**Comment by ringods** [comment]
@msiegenthaler when would the changes in the fork be integrated in this code base? Without that I'm forced to script it myself completely for one of our customers.

**Comment by ringods** [comment]
Ping @msiegenthaler. This is becoming pressing for us.

**Comment by msiegenthaler** [comment]
Hi, sorry for the delay. I can't find the time to do it this week, but if you could do a small PR for it  that'd be great. The change should be small.
Else I can probably look into it somewhen next week.

**Comment by iuriaranda** [comment]
I've created a PR for this: https://github.com/linkyard/concourse-helm-resource/pull/20
