### ISSUE TITLE
Regression: can't use local chart without tar'ing

### ISSUE THREAD

**Issue by jagregory** [linkyard/concourse-helm-resource#19]
I think this may have been undefined behaviour, or at least not explicitly supported before...

Prior to 083509953dd453166a85ca70cbaafc428cb2c1c5 you could pass a path to a chart in an input, and it didn't need to be a tar. I presume this is because `$source/$chart` would be expanded to `my-input/my/chart` which worked; however, since this change, any local charts *must* be in a tar. This is unfortunate, as in some cases my charts are committed alongside the code they're packaging.

```yaml
put: chart
  params:
    chart: git-src/chart
```

**Comment by msiegenthaler** [comment]
I probably broke this while implementing #14 , sorry about that.
Actually I'm not sure on how to implement it best - the chart you defined could also be the chart `chart` from a repo named `git-src`.
How do you think about adding a different parameter named `chartDir`? I think this would be the best way to tell to two cases apart.
