### ISSUE TITLE
Helm plugin support

### ISSUE THREAD

**Issue by TimJones** [linkyard/concourse-helm-resource#28]
It would be nice to be able to support Helm plugins for extended use.  
Our particular use-case is to add something like https://github.com/skuid/helm-value-store to manage the values based on tag selectors.  
Seeing how this is not a simple task I hope to discuss if it is even viable (supporting a generic plugin framework) or a fork supporting each plugin specifically would make more sense.

**Comment by msiegenthaler** [comment]
We'd have to build a separate image per plugin I think, I don't see a way around that.

So I think the main thing we could improve here is to somehow modularize the scripts a bit, so it's easy for an extending image to hook into certain phases of the lifecycle.
I've never used a helm plugin, so I don't feel very fit on defining possible extension points. The value-store example use case as I understand it would probably want to replace to upgrade/install commands, right?

**Comment by TimJones** [comment]
In the case of helm-value-store plugin, it only wraps the install\upgrade commands to be able to pull the 'values' from a separate backend (currently only DynamoDB is supported). Other plugins do widely different things that don't make much sense to support in a concourse resource (E.G. properly templating your chart without the need to run a `--debug --dry-run` against Tiller).  
I'm happy to help modularise the current code, helm config setup is already nicely put in `common.sh`.

**Comment by msiegenthaler** [comment]
Ok, so the best course of action would be to try to modularize all the code.
Do you think bash is still the right choice as a programming language or would you prefer a switch?

**Comment by msiegenthaler** [comment]
see #61

**Comment by amnk** [comment]
I'm using [helm-secrets](https://github.com/futuresimple/helm-secrets) plugin. Can it be added in a similar fashion? I think I can help with PR if needed.

**Comment by msiegenthaler** [comment]
Yes, the plugin sound useful. We don't use it ourselves so we'd need a PR for it.

**Comment by msiegenthaler** [comment]
I suggest we add the gcs plugin to https://github.com/linkyard/helm-chart-resource
It makes more sense to separate downloading and deploying, because that's the way concourse normally does things.

**Comment by corey-aloia-sap** [comment]
I notice that in the Dockerfile it already installs a helm plugin. It would be great if there was a 'plugins' array as input. Or, even better, if there was a hook so that someone could run a custom script :)

**Comment by msiegenthaler** [comment]
So it'd install all those plugins basically as the first step in the script, right?

What kind of plugins would you use it for? Just asking because you still won't be able to call arbitrary commands, only upgrade.

**Comment by corey-aloia-sap** [comment]
I was thinking about this today, and what would be awesome would be if we could pass a script as input which could be run before the rest of the pipeline. This would allow for doing some custom things. Like with the s3 plugin, someone could use the script to install it and to create the ~/.aws/config file which it needs. It would probably cover a lot of other scenarios as well. For example, it would allow me to do a bit of extra debugging by echoing the state of things.

**Comment by msiegenthaler** [comment]
Implemented
