### ISSUE TITLE
Unable to continue if first deployment of a release fails

### ISSUE THREAD

**Issue by aku105** [linkyard/concourse-helm-resource#32]
https://github.com/linkyard/concourse-helm-resource/blob/9f0abb6c2b988ca37da3eb6de213b8ddd33a3a51/assets/out#L225
https://github.com/linkyard/concourse-helm-resource/blob/9f0abb6c2b988ca37da3eb6de213b8ddd33a3a51/assets/out#L57-L72

If the first deployment is a failure, then `STATUS` in `helm status` will still be there (as FAILED), but helm upgrade won't work on that release because there have been no successfully deployed release that can be upgrade yet.
So, `is_deployed` should use `helm install` if the very first deployment of a helm release fails.

Not sure at the moment on how can we properly identify if at least one deployment for release is in passed state, so that we can use helm upgrade.

**Comment by aku105** [comment]
`helm history --tiller-namespace namespace "release-name" 2>&1 | grep -w DEPLOYED > /dev/null` might work.

**Comment by msiegenthaler** [comment]
Thanks, your proposal looks very good.

**Comment by msiegenthaler** [comment]
Fixed with #34
