### ISSUE TITLE
Allow to specify service_account as json

### ISSUE THREAD

**Issue by gmile** [linkyard/concourse-helm-resource#33]
It's easy to just download a JSON file containing all service account auth data. It would be great to just provide a path to this while when configuring `concourse-helm-resource`.

```json
{
  "type": "service_account",
  "project_id": "my-project-id",
  "private_key_id": "904a...",
  "private_key": "-----BEGIN PRIVATE KEY-----\n ...",
  "client_email": "my-service-account@my-project-id.iam.gserviceaccount.com",
  "client_id": "1032...",
  "auth_uri": "https://accounts.google.com/o/oauth2/auth",
  "token_uri": "https://accounts.google.com/o/oauth2/token",
  "auth_provider_x509_cert_url": "https://www.googleapis.com/oauth2/v1/certs",
  "client_x509_cert_url": "https://www.googleapis.com/robot/v1/metadata/x509/my-service-account%40my-project-id.iam.gserviceaccount.com"
}
```

**Comment by gmile** [comment]
For instance, this is how `docker-image` supports this:

```yaml
- name: my-app-in-container
  type: docker-image
  source:
    repository: eu.gcr.io/my-project-id/my-app-in-container
    username: _json_key
    password: {{gcs_service_account_json_key}}
```

**Comment by kurlzor** [comment]
It's not really the same as #36 which is kubeconfig support.
If you're using GKE, you'll need to provide this service account in addition to your kubeconfig, but it's not enough since the gcloud CLI isn't in this image.

We have our [own fork](https://github.com/Evaneos/concourse-helm-resource) with the gcloud CLI installed so we can authenticate using service accounts but I'm not sure whether something Google Cloud specific should end up in this resource. What do you think ?

**Comment by msiegenthaler** [comment]
Hm, I'd rather not have something vendor specific in it. We could have some kind of extension point where the standard common.sh calls out to a different (by default empty) script at the right place.

You need to be able to provide a kubeconfig as well? I don't use GKE, so excuse my questions..
I've seen you changed two things in you fork: allow kubeconfig and add the Google stuff, right?

**Comment by msiegenthaler** [comment]
not adding vendor specific stuff

**Comment by Cicatrice** [comment]
From [get-credentials](https://cloud.google.com/sdk/gcloud/reference/container/clusters/get-credentials) help:

> To configure a `kubeconfig` file to use application default credentials, set the `container/use_application_default_credentials` Cloud SDK property to true before running gcloud container clusters get-credentials 

So I tried to build my own tasks like following:

1. Running [google/cloud-sdk](https://hub.docker.com/r/google/cloud-sdk), I retrieve k8s credentials from my service account key file in a `creds/kubeconfig` file:

```bash
cat >creds/gcp-sa.json <<EOF
((gcp-sa.key))
EOF
GOOGLE_APPLICATION_CREDENTIALS=creds/gcp-sa.json KUBECONFIG=creds/kubeconfig \
  gcloud config set container/use_application_default_credentials true
GOOGLE_APPLICATION_CREDENTIALS=creds/gcp-sa.json KUBECONFIG=creds/kubeconfig \
  gcloud container clusters get-credentials \
    $(grep ^destination.cluster= ${MANIFEST_DIR}/keyval.properties|sed -e s/^[^=]*=//g) \
    --region $(grep ^destination.region= ${MANIFEST_DIR}/keyval.properties|sed -e s/^[^=]*=//g)
```

2. Use it in helm resource declared before, with the following parameters:
```yaml
      - put: my-helm-template
        params:
          chart: ./charts/path
          kubeconfig_path: creds/kubeconfig
```

It works out-of-the-box with [linkyard/concourse-helm-resource](https://github.com/linkyard/concourse-helm-resource) and doesn't require any change in Dockerfile nor other assets.
