### ISSUE TITLE
Error: unknown flag: --max

### ISSUE THREAD

**Issue by simonrondelez** [linkyard/concourse-helm-resource#42]
https://github.com/linkyard/concourse-helm-resource/commit/8c4ce72a9b05bf07a7d68596ba0c41bf53a58cac introduced a bug in this resource:
`helm history` has the ability to include the `--max` option since this  prints historical revisions for a given release. `helm status` not since this shows the current status of the release

**Comment by msiegenthaler** [comment]
Sorry, this was a merge mistake by me. Should be fixed in latest in a few minutes
