### ISSUE TITLE
Resource setup successful. cat: can't open '/tmp/build/put/my-redis': No such file or directory

### ISSUE THREAD

**Issue by mkotsalainen** [linkyard/concourse-helm-resource#48]
I can't get it to work with my concourse set up in a k8s cluster.

This is how my pipeline looks. I've taken away the uninteresting parts:

resource_types:
- name: helm
  type: docker-image
  source:
    repository: linkyard/concourse-helm-resource

- name: dev-cluster
  type: helm
  source:
    cluster_url: https://kubernetes
    cluster_ca: xxxxx
    admin_cert: xxxx
    admin_key: xxx

- put: dev-cluster
      params:
        chart: stable/redis
        release: my-redis

I get an error when I try to run it:

Initializing kubectl...
Cluster "default" set.
User "admin" set.
Context "default" created.
Switched to context "default".
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Initializing helm...
Client: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.8.2", GitCommit:"a80231648a1473929271764b920a8e346f6de844", GitTreeState:"clean"}
Resource setup successful.
cat: can't open '/tmp/build/put/my-redis': No such file or directory
failed

If I jump into the worker via fly intercept I can install the package via helm manually but for some reason this put won't work. Any ideas of what I'm doing wrong?

**Comment by mkotsalainen** [comment]
Ok it's this line (in the out shellscript) that is causing the cat error above:
release=`cat $source/$release_file`
When I try skip the release parameter (according to readme it is optional) I get the following error:

Running command helm upgrade --install --tiller-namespace kube-system --namespace default  stable/redis | tee /tmp/log
Error: This command needs 2 arguments: release name, chart path

**Comment by mkotsalainen** [comment]
Ok I know what is wrong now. I didn't realize that release is supposed to be a file, not a string. I'll bet a bunch of others get burned by this.

If you don't specify a release in the resource_type or the put def, you'll get the helm upgrade error I wrote about earlier. There should probably be a check there and do a regular helm install if the release param isn't present. If you want I could do a PR with that fix.

**Comment by arbourd** [comment]
I just went through this myself.

I think it should be either a file or a string. The reason I want a string is, I'm deploying many Helm charts to the same resource, with different release names.

I can see why people would want files as well.

**Comment by arbourd** [comment]
@mkotsalainen You could have a task that creates that string, dumps it in a file, and persists it to the Helm resource's `put`. That's how I'd approach it. 

Mine are not dynamic.

**Comment by msiegenthaler** [comment]
It can now be a file or a string, thanks to the PR by @arbourd

**Comment by arbourd** [comment]
@mkotsalainen I would just use the metadata resource and build a release file with the name. I'm doing that myself in a pipeline and it works fine.
