### ISSUE TITLE
Local chart dependencies need to be resolved before install

### ISSUE THREAD

**Issue by mkotsalainen** [linkyard/concourse-helm-resource#51]
If you have a chart defined in the same repo as your sourcecode being built and try to install it you will get an error like this:
Error: found in requirements.yaml, but missing in charts/ directory

The way to fix this is to do a `helm dependency up` for local files before you run the helm upgrade --install command.

Anybody else have another solution? Except for hosting the chart somewhere outside the local code repo that is.

**Comment by mkotsalainen** [comment]
I have a simple fix for this: https://github.com/mkotsalainen/concourse-helm-resource/commit/b75533b9fd05144809769d813202724381bdb5f7

**Comment by duboisph** [comment]
Submitted PR since we've been hitting this issue recently too: https://github.com/linkyard/concourse-helm-resource/pull/123
