### ISSUE TITLE
helm history fails with large message when lots of releases

### ISSUE THREAD

**Issue by jagregory** [linkyard/concourse-helm-resource#58]
If a release has a lot of history doing a `helm history` will fail with a large message error:

```
> helm history prometheus
Error: grpc: trying to send message larger than max (22395781 vs. 20971520)
```

The implementation of `current_revision` has this issue so builds are failing after they've pushed to tiller.

```sh
current_revision() {
  helm history --tiller-namespace $tiller_namespace $release | grep "DEPLOYED" | awk '{ print $1 }'
}
```

I think adding a `--max 1` would be sufficient to fix this, as max always returns the latest revision.

**Comment by msiegenthaler** [comment]
I used `--max 20` in case the last is not deployed.
