### ISSUE TITLE
wait-for-helm resource type matching incomplete/too strict

### ISSUE THREAD

**Issue by jagregory** [linkyard/concourse-helm-resource#6]
The matching in `parseResource` of [parse-helm.ts](https://github.com/linkyard/concourse-helm-resource/blob/master/wait-for-helm-deployment/src/parse-helm.ts) needs some love. The types switched on are incomplete or too strict, depending on how you look at it. If you're running a newer or older version of Kube, the types may be different. The current implementation seems like it'll be brittle and require constant supervision.

Specifically, my Kube deploy has `extensions/v1beta1/Deployment` as the type for Deployments. The impact is wait-for-helm doesn't actually wait until everything has been created, so the pipeline continues and blows up later because the release isn't actually deployed properly. I've forked and done a hacky fix to solve my immediate issue (see: [L67](https://github.com/jagregory/concourse-helm-resource/blob/patch-1/wait-for-helm-deployment/src/parse-helm.ts#L67)) but this doesn't feel sustainable.

What are your thoughts on a future proof implementation? I'm happy to send a PR over.

I'm thinking options:

  1. Match only on the last part of the type, e.g. `Deployment`. The downside of this is if ever there's any double up in type suffixes we might have to disambiguate.
  2. Query Kube directly instead, this way we could switch on the `kind` field and not worry about the API versions. This'd be a much bigger change though, as we'd need kubectl and a reliable way to query all resources created by the chart etc...

**Comment by msiegenthaler** [comment]
I suggest we just use the --wait flag on helm (see https://github.com/kubernetes/helm/blob/master/docs/using_helm.md).

It was not available when I first wrote the helm resource type, but they since introduced it. This allows us to get rid of quite some code.

**Comment by jagregory** [comment]
That sounds quite sensible. Unfortunately, the wait flag is currently
broken or unstable: https://github.com/kubernetes/helm/issues/2426

I actually started by using helm --wait in a custom task before discovering
this resource., and I stopped because --wait wasn't working reliably.

**Comment by msiegenthaler** [comment]
I've prepared a PR that will use the --wait flag, but let's wait until helm fixes the issue.

Until then I suggest we just do a matching on the last part. A kube query would be cleaner, but since it's throwaway code anyway we should not do too much work on it.
I'll prepare a PR
