### ISSUE TITLE
Tiller TLS support

### ISSUE THREAD

**Issue by brunoban** [linkyard/concourse-helm-resource#69]
As far as I could see, with this resource it's not possible to deploy to a Tiller install that uses TLS to connect, is it? 

I couldn't find any `--tls` flags in any of the resources and I thought this was seen as a best practice, am I missing something? I will do it myself and submit a PR, was just wondering if I am not interpreting something incorrectly.

Thanks!

**Comment by msiegenthaler** [comment]
Yes, that's true. We'd be very interested to get that PR.

**Comment by brunoban** [comment]
Ok then. I'll get on it.
