### ISSUE TITLE
gitlab config

### ISSUE THREAD

**Issue by jonatasoli** [linkyard/concourse-helm-resource#79]
Hello,

I'm trying to use a private repository of gitlab where my chart is, but I can not put a token or private_key to connect. Is there a solution?

Thanks,
Jônatas

**Comment by msiegenthaler** [comment]
Yes, you need to get the chart as a different resource (i.e. git) and then use the chart-file in this resource. For most use cases this makes more sense than directly referring to the chart from within this resource.
Else this resource basically represents two different resources:
- the chart (version of the chart)
- the deployment of the chart (revision of the deployment)
