### ISSUE TITLE
Create new release from Master

### ISSUE THREAD

**Issue by Typositoire** [linkyard/concourse-helm-resource#83]
It'd be nice to get a release with the output fix. https://github.com/linkyard/concourse-helm-resource/pull/82

**Comment by msiegenthaler** [comment]
Sure, I've created 2.9.1-4, give it a few minutes until it's built and on Dockerhub

**Comment by Typositoire** [comment]
thanks! If you need help maintaining the repo I'd be glade to help btw.

**Comment by msiegenthaler** [comment]
What would be really really great if we had some tests. We can provide a kubernetes cluster for the builds and set that up, but I'll need some help for designing and implementing the tests.
So if you could do a proposal in that direction it'd be really great and very much appreciated.
