### ISSUE TITLE
Why is `helm repo update` called many times?

### ISSUE THREAD

**Issue by arbourd** [linkyard/concourse-helm-resource#88]
On line 145 `helm repo update` is called many times, once for each repo. Would it not make sense to call once, after the loop of adds? Anything I'm missing?

https://github.com/linkyard/concourse-helm-resource/blob/0ce1523f5a5072d0d0909e7e28c3acb7113ba585/assets/common.sh#L133-L146

**Comment by msiegenthaler** [comment]
Yeah, makes sense, no point in calling it many times.
