### ISSUE TITLE
Unable to specify helm client version

### ISSUE THREAD

**Issue by frank-bader** [linkyard/concourse-helm-resource#90]
There's no option to specify the helm client version.
This is needed to match the helm server version on an enterprise cluster that might not always be up to the latest version, otherwise the build errors out if the versions don't match.
It is harder to force the server version to match the client than the other way around.
I think this can be done by modifying the Dockerfile to something like:
ARG HELM_VERSION=latest
FROM linkyard/docker-helm:$HELM_VERSION

Then in the put we can add something like:
build_args:
  HELM_VERSION: 2.9.1

**Comment by danielsand** [comment]
this is a deploy breaker - this can break easily the pipeline if a new helm version was deployed.

which just happend for me :D

**Comment by msiegenthaler** [comment]
Do you have an own Build of this resource?
Else I’d just advise you to use a tagged version (see releases) of this resource instead of latest.
We version then based on the Helm version.

**Comment by frank-bader** [comment]
> Do you have an own Build of this resource?
> Else I’d just advise you to use a tagged version (see releases) of this resource instead of latest.
> We version then based on the Helm version.

There seems to be a bunch of other changes rolled in with the version releases. I tried the older tag and got a bunch of errors.
I think having the option to specify the client version is the more flexible way to go so you don't lose other fixes.
I can certainly checkout and have our own build and try the version changes locally.

**Comment by msiegenthaler** [comment]
Hm, that is strange, you should be able use the `2.9.1-3` tag or probably better to `2.10.0`

**Comment by msiegenthaler** [comment]
Could you open a PR for the ARG change? But please use `2.11.0` instead of `latest` for the default tag

**Comment by msiegenthaler** [comment]
I'd now suggest you use tillerless, it works around the problem rather elegantly by not even requiring a tiller...
